#ifdef LIGHTING_FALLOFF
#undef LIGHTING_FALLOFF
#endif
#ifdef LIGHTING_LAMBERTIAN
#undef LIGHTING_LAMBERTIAN
#endif
#ifdef LIGHTING_HEIGHT
#undef LIGHTING_HEIGHT
#endif

#ifdef LIGHTING_RESOLUTION
#undef LIGHTING_RESOLUTION
#endif
#ifdef LIGHTING_ICON
#undef LIGHTING_ICON
#endif

#ifdef LIGHTING_BASE_MATRIX
#undef LIGHTING_BASE_MATRIX
#endif
