/*
 * Infernal Research
 *
 * This is deliberately a self-contained research loop:
 *   1. Print an infernal field sampler from a protolathe.
 *   2. Collect a demon specimen, artifact impression, or Hellwave recording.
 *   3. Use the matching research appliance to mint a normal technology disk.
 *   4. Upload that disk at an R&D console to advance ordinary science paths.
 *
 * The three appliances are intentionally distinct sources of technology disks.
 * They are not upgrades of the ordinary R&D disk printer and do not need an
 * empty disk; the researched phenomenon writes its own substrate. Every disk
 * stores an existing, conventional technology datum rather than a new tech tree.
 */

/proc/create_hell_derived_tech_disk(var/atom/location, var/list/tech_types, var/research_level, var/method)
	var/turf/output_turf = get_turf(location)
	if(!output_turf || !tech_types || !tech_types.len)
		return null
	var/tech_type = pick(tech_types)
	var/obj/item/disk/tech_disk/disk = new /obj/item/disk/tech_disk(output_turf)
	var/datum/tech/technology = new tech_type(disk)
	technology.level = between(1, research_level, 20)
	disk.stored = technology
	disk.name = "[technology.name] technology disk ([technology.level])"
	disk.desc = "A technology disk generated by [method]. It contains level [technology.level] data for ordinary [technology.name] research."
	return disk


/proc/is_infernal_research_subject(var/atom/target)
	if(istype(target, /mob/living/simple_animal))
		var/mob/living/simple_animal/animal = target
		if(animal.supernatural)
			return TRUE
	if(ismob(target))
		var/mob/M = target
		var/lower_name = lowertext(M.name)
		if(findtext(lower_name, "demon") || findtext(lower_name, "infernal") || findtext(lower_name, "hell"))
			return TRUE
	return FALSE


/proc/is_infernal_research_site(var/atom/target)
	if(istype(target, /obj/effect/rune) || istype(target, /obj/structure/hellheart))
		return TRUE
	if(istype(target, /turf/simulated/floor/helldirt) || istype(target, /turf/simulated/floor/hellslate))
		return TRUE
	if(istype(target, /turf/unsimulated/hellwall) || istype(target, /turf/unsimulated/wall/cult))
		return TRUE
	var/turf/T = get_turf(target)
	if(T && (istype(T, /turf/simulated/floor/helldirt) || istype(T, /turf/simulated/floor/hellslate)))
		return TRUE
	return FALSE


/obj/item/infernal_sample
	name = "unclassified infernal sample"
	desc = "A sealed sample whose contents refuse ordinary classification."
	icon = 'icons/obj/cloning.dmi'
	icon_state = "datadisk2"
	item_state = "card-id"
	w_class = ITEM_SIZE_SMALL
	var/sample_origin = "unknown source"

/obj/item/infernal_sample/attack_self(var/mob/user)
	to_chat(user, "<span class='notice'>The label reads: [sample_origin].</span>")

/obj/item/infernal_sample/demon
	name = "demonological specimen"
	desc = "A containment ampoule full of impossible tissue and residual intent. Feed it to a demonological sequencer."

/obj/item/infernal_sample/artifact
	name = "artifact resonance impression"
	desc = "A crystalline recording of an artifact's impossible geometry. Feed it to a reliquary covenant reader."

/obj/item/infernal_sample/hellwave
	name = "Hellwave recording"
	desc = "A recording of the pressure, heat, and backwards whispers emitted by Hell. Feed it to a Hellwave entanglement array."


/obj/item/device/infernal_field_sampler
	name = "infernal field sampler"
	desc = "A hand-held xenological sampler. Use it on a demon, alien artifact, or Hell-tainted site to capture a research sample."
	icon = 'icons/obj/device.dmi'
	icon_state = "analyzer"
	item_state = "analyzer"
	w_class = ITEM_SIZE_SMALL
	origin_tech = list(TECH_DATA = 2, TECH_MAGNET = 1)

/obj/item/device/infernal_field_sampler/afterattack(var/atom/target, var/mob/user, var/proximity)
	if(!proximity)
		return
	var/sample_type = null
	if(istype(target, /obj/machinery/artifact))
		sample_type = /obj/item/infernal_sample/artifact
	else if(is_infernal_research_subject(target))
		sample_type = /obj/item/infernal_sample/demon
	else if(is_infernal_research_site(target))
		sample_type = /obj/item/infernal_sample/hellwave
	if(!sample_type)
		to_chat(user, "<span class='warning'>The sampler finds no infernal signature in \the [target].</span>")
		return
	var/obj/item/infernal_sample/sample = new sample_type(get_turf(user))
	sample.sample_origin = "sampled from [target.name]"
	if(!user.put_in_hands(sample))
		sample.forceMove(get_turf(user))
	user.visible_message("<span class='notice'>\The [user] captures a research sample from \the [target].</span>", "<span class='notice'>The sampler bottles an infernal signature from \the [target].</span>")


/obj/machinery/infernal_research
	name = "infernal research appliance"
	desc = "A machine intended for studying things that should not be studied."
	icon = 'icons/obj/modular_console.dmi'
	icon_state = "cs_db"
	density = 1
	anchored = 1
	idle_power_usage = 20
	active_power_usage = 1500

/obj/machinery/infernal_research/proc/handle_standard_parts(var/obj/item/tool, var/mob/user)
	if(default_deconstruction_screwdriver(user, tool))
		return TRUE
	if(default_deconstruction_crowbar(user, tool))
		return TRUE
	if(default_part_replacement(user, tool))
		return TRUE
	return FALSE

/obj/machinery/infernal_research/proc/can_perform_research(var/mob/user)
	if(stat & (NOPOWER|BROKEN))
		to_chat(user, "<span class='warning'>\The [src] is not receiving enough power to contain the result.</span>")
		return FALSE
	return TRUE

/obj/machinery/infernal_research/proc/hand_disk_to_researcher(var/mob/user, var/list/tech_types, var/research_level, var/method)
	var/obj/item/disk/tech_disk/disk = create_hell_derived_tech_disk(src, tech_types, research_level, method)
	if(!disk)
		to_chat(user, "<span class='warning'>The apparatus cannot form a stable disk substrate here.</span>")
		return FALSE
	if(!user.put_in_hands(disk))
		disk.forceMove(get_turf(src))
	use_power_oneoff(active_power_usage)
	return TRUE


// DISK CREATION METHOD #1: sequence a demonological field specimen.
/obj/machinery/infernal_research/demonological_sequencer
	name = "demonological sequencer"
	desc = "Sequences the biology, intent, and unlicensed metaphysics of demonic specimens. Insert a demonological specimen, then activate it to grow a technology disk."
	var/obj/item/infernal_sample/demon/loaded_specimen = null

/obj/machinery/infernal_research/demonological_sequencer/New()
	..()
	component_parts = list()
	component_parts += new /obj/item/circuitboard/demonological_sequencer(src)
	component_parts += new /obj/item/stock_parts/scanning_module(src)
	component_parts += new /obj/item/stock_parts/manipulator(src)
	component_parts += new /obj/item/stock_parts/micro_laser(src)

/obj/machinery/infernal_research/demonological_sequencer/attackby(var/obj/item/tool, var/mob/user)
	if(handle_standard_parts(tool, user))
		return
	if(!istype(tool, /obj/item/infernal_sample/demon))
		to_chat(user, "<span class='warning'>The sequencer only accepts demonological specimens.</span>")
		return
	if(loaded_specimen)
		to_chat(user, "<span class='warning'>The sequencer already contains \a [loaded_specimen].</span>")
		return
	user.drop_item()
	tool.forceMove(src)
	loaded_specimen = tool
	to_chat(user, "<span class='notice'>You load \the [tool] into \the [src]. Activate it with an empty hand to sequence the specimen.</span>")

/obj/machinery/infernal_research/demonological_sequencer/attack_hand(var/mob/user)
	if(!can_perform_research(user) || !loaded_specimen)
		if(!loaded_specimen)
			to_chat(user, "<span class='notice'>The sequencer awaits a demonological specimen.</span>")
		return
	var/origin = loaded_specimen.sample_origin
	qdel(loaded_specimen)
	loaded_specimen = null
	if(hand_disk_to_researcher(user, list(/datum/tech/biotech, /datum/tech/combat, /datum/tech/materials, /datum/tech/engineering), 7, "demonological sequencing of [origin]"))
		visible_message("<span class='warning'>\The [src] condenses a demonological specimen into a conventional technology disk.</span>")


// DISK CREATION METHOD #2: decode an artifact resonance impression.
/obj/machinery/infernal_research/reliquary_covenant_reader
	name = "reliquary covenant reader"
	desc = "Decodes artifact resonance impressions into contractual mathematics. Insert an artifact resonance impression, then activate it to grow a technology disk."
	var/obj/item/infernal_sample/artifact/loaded_impression = null

/obj/machinery/infernal_research/reliquary_covenant_reader/New()
	..()
	component_parts = list()
	component_parts += new /obj/item/circuitboard/reliquary_covenant_reader(src)
	component_parts += new /obj/item/stock_parts/scanning_module(src)
	component_parts += new /obj/item/stock_parts/scanning_module(src)
	component_parts += new /obj/item/stock_parts/capacitor(src)

/obj/machinery/infernal_research/reliquary_covenant_reader/attackby(var/obj/item/tool, var/mob/user)
	if(handle_standard_parts(tool, user))
		return
	if(!istype(tool, /obj/item/infernal_sample/artifact))
		to_chat(user, "<span class='warning'>The reader only accepts artifact resonance impressions.</span>")
		return
	if(loaded_impression)
		to_chat(user, "<span class='warning'>The reader already contains \a [loaded_impression].</span>")
		return
	user.drop_item()
	tool.forceMove(src)
	loaded_impression = tool
	to_chat(user, "<span class='notice'>You load \the [tool] into \the [src]. Activate it with an empty hand to interpret the artifact's covenant.</span>")

/obj/machinery/infernal_research/reliquary_covenant_reader/attack_hand(var/mob/user)
	if(!can_perform_research(user) || !loaded_impression)
		if(!loaded_impression)
			to_chat(user, "<span class='notice'>The reader awaits an artifact resonance impression.</span>")
		return
	var/origin = loaded_impression.sample_origin
	qdel(loaded_impression)
	loaded_impression = null
	if(hand_disk_to_researcher(user, list(/datum/tech/bluespace, /datum/tech/magnets, /datum/tech/powerstorage, /datum/tech/programming), 13, "artifact covenant analysis of [origin]"))
		visible_message("<span class='warning'>\The [src] translates an alien artifact into a conventional technology disk.</span>")


// DISK CREATION METHOD #3: entangle a Hellwave recording with a stable data substrate.
/obj/machinery/infernal_research/hellwave_entanglement_array
	name = "Hellwave entanglement array"
	desc = "Listens to recordings made at Hell-tainted sites and resolves the backwards signal into data. Insert a Hellwave recording, then activate it to grow a technology disk."
	var/obj/item/infernal_sample/hellwave/loaded_recording = null

/obj/machinery/infernal_research/hellwave_entanglement_array/New()
	..()
	component_parts = list()
	component_parts += new /obj/item/circuitboard/hellwave_entanglement_array(src)
	component_parts += new /obj/item/stock_parts/micro_laser(src)
	component_parts += new /obj/item/stock_parts/micro_laser(src)
	component_parts += new /obj/item/stock_parts/capacitor(src)

/obj/machinery/infernal_research/hellwave_entanglement_array/attackby(var/obj/item/tool, var/mob/user)
	if(handle_standard_parts(tool, user))
		return
	if(!istype(tool, /obj/item/infernal_sample/hellwave))
		to_chat(user, "<span class='warning'>The array only accepts Hellwave recordings.</span>")
		return
	if(loaded_recording)
		to_chat(user, "<span class='warning'>The array already contains \a [loaded_recording].</span>")
		return
	user.drop_item()
	tool.forceMove(src)
	loaded_recording = tool
	to_chat(user, "<span class='notice'>You load \the [tool] into \the [src]. Activate it with an empty hand to resolve the signal.</span>")

/obj/machinery/infernal_research/hellwave_entanglement_array/attack_hand(var/mob/user)
	if(!can_perform_research(user) || !loaded_recording)
		if(!loaded_recording)
			to_chat(user, "<span class='notice'>The array awaits a Hellwave recording.</span>")
		return
	var/origin = loaded_recording.sample_origin
	qdel(loaded_recording)
	loaded_recording = null
	if(hand_disk_to_researcher(user, list(/datum/tech/phorontech, /datum/tech/powerstorage, /datum/tech/bluespace, /datum/tech/magnets), 20, "Hellwave entanglement of [origin]"))
		visible_message("<span class='warning'>\The [src] screams in reverse and deposits a conventional technology disk.</span>")


/*
 * Fabrication access. The sampler and the three appliance boards deliberately
 * use ordinary science prerequisites: each disk route is reachable before a
 * research team has found any infernal evidence.
 */

/datum/design/item/infernal_field_sampler
	name = "infernal field sampler"
	desc = "Produce a sampler for extracting demon, artifact, and Hellwave research specimens."
	id = "infernal_field_sampler"
	req_tech = list(TECH_DATA = 2, TECH_MAGNET = 1)
	materials = list(DEFAULT_WALL_MATERIAL = 120, "glass" = 80)
	build_path = /obj/item/device/infernal_field_sampler
	sort_string = "INFRA"

/datum/design/circuit/demonological_sequencer
	name = "demonological sequencer"
	id = "demonological_sequencer"
	req_tech = list(TECH_DATA = 2, TECH_BIO = 2, TECH_MAGNET = 2)
	build_path = /obj/item/circuitboard/demonological_sequencer
	sort_string = "INFRAA"

/datum/design/circuit/reliquary_covenant_reader
	name = "reliquary covenant reader"
	id = "reliquary_covenant_reader"
	req_tech = list(TECH_DATA = 2, TECH_BLUESPACE = 2, TECH_MAGNET = 2)
	build_path = /obj/item/circuitboard/reliquary_covenant_reader
	sort_string = "INFRAB"

/datum/design/circuit/hellwave_entanglement_array
	name = "Hellwave entanglement array"
	id = "hellwave_entanglement_array"
	req_tech = list(TECH_DATA = 3, TECH_MAGNET = 3)
	build_path = /obj/item/circuitboard/hellwave_entanglement_array
	sort_string = "INFRAC"


/obj/item/circuitboard/demonological_sequencer
	name = T_BOARD("demonological sequencer")
	build_path = /obj/machinery/infernal_research/demonological_sequencer
	board_type = "machine"
	origin_tech = list(TECH_DATA = 2, TECH_BIO = 2, TECH_MAGNET = 2)
	req_components = list(
		/obj/item/stock_parts/scanning_module = 1,
		/obj/item/stock_parts/manipulator = 1,
		/obj/item/stock_parts/micro_laser = 1)

/obj/item/circuitboard/reliquary_covenant_reader
	name = T_BOARD("reliquary covenant reader")
	build_path = /obj/machinery/infernal_research/reliquary_covenant_reader
	board_type = "machine"
	origin_tech = list(TECH_DATA = 2, TECH_BLUESPACE = 2, TECH_MAGNET = 2)
	req_components = list(
		/obj/item/stock_parts/scanning_module = 2,
		/obj/item/stock_parts/capacitor = 1)

/obj/item/circuitboard/hellwave_entanglement_array
	name = T_BOARD("Hellwave entanglement array")
	build_path = /obj/machinery/infernal_research/hellwave_entanglement_array
	board_type = "machine"
	origin_tech = list(TECH_DATA = 3, TECH_MAGNET = 3)
	req_components = list(
		/obj/item/stock_parts/micro_laser = 2,
		/obj/item/stock_parts/capacitor = 1)
