#define STAT_ST "st"
#define STAT_DX "dx"
#define STAT_IQ "iq"
#define STAT_HT "ht"
#define STAT_PER "per"

#define PERCEPTION_STAT_FLOOR 2
#define PERCEPTION_CHANCE_PER_POINT 15
#define PERCEPTION_CHANCE_PER_MOD 3
#define PERCEPTION_OPPOSED_BASE 50
#define PERCEPTION_OPPOSED_PER_POINT 8
#define PERCEPTION_CHANCE_MIN 5
#define PERCEPTION_CHANCE_MAX 95